version: '3.3'
services:
    romm:
        container_name: romm
        network_mode: romm
        environment:
            - TZ=America/Los_Angeles
            - HOST_OS=Unraid
            - HOST_HOSTNAME={placeholder}
            - HOST_CONTAINERNAME=romm
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_NAME=romm
            - DB_USER=romm
            - DB_PASSWD={placeholder}
            - ROMM_AUTH_SECRET_KEY={placeholder}
            - IGDB_CLIENT_ID={placeholder}
            - IGDB_CLIENT_SECRET={placeholder}
            - SCREENSCRAPER_USER=
            - SCREENSCRAPER_PASSWORD=
            - MOBYGAMES_API_KEY=
            - STEAMGRIDDB_API_KEY={placeholder}
            - RETROACHIEVEMENTS_API_KEY={placeholder}
            - REFRESH_RETROACHIEVEMENTS_CACHE_DAYS=
            - LAUNCHBOX_API_ENABLED=false
            - PLAYMATCH_API_ENABLED=false
            - HASHEOUS_API_ENABLED=true
            - FLASHPOINT_API_ENABLED=false
            - HLTB_API_ENABLED=false
            - ROMM_DB_DRIVER=mariadb
            - DB_QUERY_JSON=
            - REDIS_HOST=
            - REDIS_PORT=
            - REDIS_USERNAME=
            - REDIS_PASSWORD=
            - REDIS_DB=
            - REDIS_SSL=
            - DISABLE_CSRF_PROTECTION=false
            - DISABLE_DOWNLOAD_ENDPOINT_AUTH=false
            - DISABLE_USERPASS_LOGIN=false
            - SESSION_MAX_AGE_SECONDS=
            - KIOSK_MODE=false
            - OIDC_ENABLED=false
            - OIDC_PROVIDER=
            - OIDC_CLIENT_ID=
            - OIDC_CLIENT_SECRET=
            - OIDC_REDIRECT_URI=
            - OIDC_SERVER_APPLICATION_URL=
            - OIDC_TLS_CACERTFILE=
            - WEB_SERVER_CONCURRENCY=
            - WEB_SERVER_KEEPALIVE=
            - WEB_SERVER_MAX_REQUESTS=
            - WEB_SERVER_MAX_REQUESTS_JITTER=
            - WEB_SERVER_TIMEOUT=
            - WEB_SERVER_WORKER_CONNECTIONS=
            - FORCE_COLOR=
            - NO_COLOR=
            - DISABLE_EMULATOR_JS=false
            - DISABLE_RUFFLE_RS=false
            - YOUTUBE_BASE_URL=
            - UPLOAD_TIMEOUT=
            - SCAN_TIMEOUT=
            - SCAN_WORKERS=
            - TASK_TIMEOUT=
            - TASK_RESULT_TTL=
            - SEVEN_ZIP_TIMEOUT=
            - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=false
            - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=
            - ENABLE_SCHEDULED_RESCAN=false
            - SCHEDULED_RESCAN_CRON=
            - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=false
            - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=
            - ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA=false
            - SCHEDULED_UPDATE_LAUNCHBOX_METADATA_CRON=
            - ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP=false
            - SCHEDULED_CONVERT_IMAGES_TO_WEBP_CRON=
            - ENABLE_SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC=false
            - SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC_CRON=
            - LOGLEVEL=INFO
            - SENTRY_DSN=
            - CA_TS_FALLBACK_DIR=/romm/library/
        ports:
            - '8080:8080/tcp'
        volumes:
            - '/mnt/user/RomM/:/romm/library/:rw'
            - '/mnt/user/appdata/romm/resources:/romm/resources/:rw'
            - '/mnt/user/appdata/romm/assets:/romm/assets/:rw'
            - '/mnt/user/appdata/romm/config:/romm/config/:rw'
            - '/mnt/user/appdata/romm/redis-data:/redis-data:rw'
        image: 'rommapp/romm:latest'